apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: chatapp-ingress
  namespace: chat-app
  labels:
    app: chatapp
  annotations:
    # Traefik WebSocket support
    traefik.ingress.kubernetes.io/websocket-services: "socket-service"
    # Route via HTTP entrypoint
    traefik.ingress.kubernetes.io/router.entrypoints: "web"
spec:
  ingressClassName: traefik
  rules:
  - host: ec2-13-219-252-189.compute-1.amazonaws.com
    http:
      paths:
        - path: /socket.io
          pathType: Prefix
          backend:
            service:
              name: socket-service
              port:
                number: 5004
        - path: /api
          pathType: Prefix
          backend:
            service:
              name: backend
              port:
                number: 5001
        - path: /
          pathType: Prefix
          backend:
            service:
              name: frontend
              port:
                number: 80
